# Generated by Django 5.0 on 2024-02-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='phone_number',
            field=models.CharField(default='0746162126', max_length=20, unique=True),
        ),
    ]
