# Generated by Django 5.0 on 2024-02-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0004_rename_first_name_newuser_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
