# Generated by Django 5.0 on 2024-02-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0005_newuser_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='first_name',
        ),
    ]
