# Generated by Django 5.0 on 2024-02-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0006_remove_newuser_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
