# Generated by Django 5.0 on 2024-04-16 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_module', '0002_conveyance_extracted_text_conveyance_summarized_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conveyance',
            name='extracted_text',
        ),
        migrations.RemoveField(
            model_name='conveyance',
            name='summarized_text',
        ),
        migrations.CreateModel(
            name='AnalyzedConveyance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_text', models.TextField(blank=True)),
                ('summarized_text', models.TextField(blank=True)),
                ('conveyance_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf_module.conveyance')),
            ],
        ),
    ]
