# Generated by Django 5.0 on 2024-04-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_module', '0004_remove_analyzedconveyance_conveyance_doc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conveyance',
            name='analyzed_doc',
        ),
        migrations.AddField(
            model_name='conveyance',
            name='extracted_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='conveyance',
            name='summarized_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='conveyance',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='AnalyzedConveyance',
        ),
    ]
