# Generated by Django 5.0 on 2024-04-16 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_module', '0005_remove_conveyance_analyzed_doc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conveyance',
            old_name='updated',
            new_name='file_update_date',
        ),
        migrations.RenameField(
            model_name='conveyance',
            old_name='uploaded',
            new_name='file_upload_date',
        ),
        migrations.RemoveField(
            model_name='conveyance',
            name='extracted_text',
        ),
        migrations.RemoveField(
            model_name='conveyance',
            name='summarized_text',
        ),
        migrations.AlterField(
            model_name='conveyance',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.CreateModel(
            name='AnalyzedConveyance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_text', models.TextField(null=True)),
                ('summarized_text', models.TextField(null=True)),
                ('text_extraction_date', models.DateTimeField(auto_now_add=True)),
                ('text_extraction_update', models.DateTimeField(auto_now=True)),
                ('conveyance_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf_module.conveyance')),
            ],
        ),
    ]
