# Generated by Django 5.0 on 2024-04-17 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_module', '0006_rename_updated_conveyance_file_update_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyzedconveyance',
            name='conveyance_doc',
        ),
        migrations.AddField(
            model_name='analyzedconveyance',
            name='conveyance',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pdf_module.conveyance'),
        ),
    ]
