# Generated by Django 5.0 on 2024-05-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_module', '0012_alter_analyzedconveyance_conveyance'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedconveyance',
            name='analyzed_file',
            field=models.FileField(blank=True, null=True, upload_to='analyzed/'),
        ),
    ]
