# Generated by Django 5.0 on 2024-05-12 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_module', '0015_alter_analyzedconveyance_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyzedconveyance',
            name='user',
        ),
    ]
