# Generated by Django 5.0 on 2024-02-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
