# Generated by Django 5.0 on 2024-02-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApi', '0004_alter_newuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
    ]
