# Generated by Django 5.0 on 2024-02-06 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApi', '0006_alter_newuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='phone_number',
        ),
    ]
